export const ADD_BOOK_TO_SHELF = "ADD_BOOK_TO_SHELF";
export const REMOVE_BOOK_FROM_SHELF = "REMOVE_BOOK_FROM_SHELF";
export const ADD_SHELF = "ADD_SHELF";
export const REMOVE_SHELF = "REMOVE_SHELF";
export const SET_SHELF_REVIEW = "SET_SHELF_REVIEW";
export const SET_SHELF_CATEGORY = "SET_SHELF_CATEGORY";
