export const ADD_BOOK_TO_SHELVE = "ADD_BOOK_TO_SHELVE";
export const REMOVE_BOOK_FROM_SHELVE = "REMOVE_BOOK_FROM_SHELVE";
export const ADD_SHELVE = "ADD_SHELVE";
export const REMOVE_SHELVE = "REMOVE_SHELVE";
export const SET_SHELVE_REVIEW = "SET_SHELVE_REVIEW";
export const SET_SHELVE_CATEGORY = "SET_SHELVE_CATEGORY";
